# -*- coding: utf-8 -*-
"""client (simple chat over a network with encrypted messaging).ipynb

Automatically generated by Colab.

"""

import socket  # Networking
from cryptography.fernet import Fernet  # Encryption

# ==============================
# CLIENT CONNECTION SETUP
# ==============================

# Replace with server's IP address
# If running locally, keep 127.0.0.1
HOST = '127.0.0.1'
PORT = 5555

# ==============================
# ENCRYPTION SETUP
# ==============================

# Paste the key printed by the server here
# MUST match exactly, or decryption will fail
input_value = input("Paste the key here: ")
key = input_value


# Create cipher using shared key
cipher = Fernet(key)

# ==============================
# CONNECT TO SERVER
# ==============================

# Create TCP socket
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Connect to the server
client.connect((HOST, PORT))

print("Connected to server.")

# ==============================
# CHAT LOOP
# ==============================

while True:
    try:
        # Get user input
        msg = input("You: ")

        # Encrypt message before sending
        encrypted_msg = cipher.encrypt(msg.encode())

        # Send encrypted data
        client.send(encrypted_msg)

        # Wait for server reply
        encrypted_reply = client.recv(1024)

        # If no data, server disconnected
        if not encrypted_reply:
            print("Server disconnected.")
            break

        # Decrypt incoming message
        decrypted_reply = cipher.decrypt(encrypted_reply).decode()

        print(f"Server: {decrypted_reply}")

    except Exception as e:
        print("Error:", e)
        break

# Close connection
client.close()
