# -*- coding: utf-8 -*-
"""server (simple chat over a network with encrypted messaging).ipynb

Automatically generated by Colab.

"""

import socket  # Provides low-level networking interface
from cryptography.fernet import Fernet  # Simple symmetric encryption tool

# ==============================
# ENCRYPTION SETUP
# ==============================

# Generate a new secret key
# This key must be shared with the client securely
# Whoever has this key can encrypt/decrypt messages
key = Fernet.generate_key()

# Create a Fernet cipher object using the key
cipher = Fernet(key)

# Display the key so you can copy it into the client
print("=== SHARE THIS KEY WITH CLIENT SECURELY ===")
print(key.decode())
print("===========================================")

# ==============================
# SERVER SETUP
# ==============================

# Define IP address and port
# 0.0.0.0 means "listen on all network interfaces"
HOST = '0.0.0.0'
PORT = 5555

# Create a TCP socket
server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Bind the socket to the address and port
server.bind((HOST, PORT))

# Start listening for incoming connections
# Argument (1) = max number of queued connections
server.listen(1)

print(f"Server listening on {HOST}:{PORT}...")

# Wait (block) until a client connects
conn, addr = server.accept()

# conn = socket for communication with this client
# addr = client's address (IP, port)
print(f"Connected to client: {addr}")

# ==============================
# CHAT LOOP
# ==============================

while True:
    try:
        # Receive encrypted data from client
        # 1024 bytes = max chunk size
        encrypted_msg = conn.recv(1024)

        # If no data received, client disconnected
        if not encrypted_msg:
            print("Client disconnected.")
            break

        # Decrypt message using shared key
        decrypted_msg = cipher.decrypt(encrypted_msg).decode()

        print("Client: " + decrypted_msg)

        # Get user input from server side
        msg = input("You: ")

        # Encrypt message before sending
        encrypted_reply = cipher.encrypt(msg.encode())

        # Send encrypted message to client
        conn.send(encrypted_reply)

    except Exception as e:
        # Catch errors (e.g., bad encryption, disconnects)
        print("Error:", e)
        break

# Close connection cleanly
conn.close()
server.close()
